source 'http://rubygems.org'

gem 'rails', '3.0.1'
gem 'autotest','4.4.6'

gem 'sqlite3-ruby', :require => 'sqlite3'
 group :development do
   gem 'rspec-rails','2.0.0.beta.18'
   gem 'annotate','2.4.0'
 end
group :test do
   gem 'rspec','2.0.0.beta.18'
   gem 'webrat','0.7.1'
   gem 'spork', '0.9.0'
   gem 'factory_girl_rails', '1.0'
end
